baseURL = 'https://slavamoskvin.com'
languageCode = 'en-us'
title = "Slava Moskvin"
theme = 'hyde'


[permalinks]
  posts = '/:slug/'


[params]
  AuthorName = 'Slava Moskvin'
  SidebarRecentLimit = 5
  description = "Reverse Engineering and Offensive Security"
  avatar='/IMG_2021-3-16.jpeg'
  #layoutReverse = true

[Menus]
  main = [
      {Name = "ğŸ¦ Twitter", URL = "https://twitter.com/slava_moskvin_"},
      {Name = "ğŸŒ LinkedIn", URL = "https://www.linkedin.com/in/vyacheslav-moskvin/"},
      {Name = "ğŸ”´ YouTube", URL = "https://www.youtube.com/c/PathCybersecSlavaMoskvin"}
  ]

[menu]
# [[menu.main]]
#     name = 'About'
#     pageRef = '/about'
#     weight = 20
